export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const CHANGE_TODO_STATUS = "CHANGE_TODO_STATUS";

export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAIL = "GET_TODOS_FAIL";

export const SEND_TODO_REQUEST = "SEND_TODO_REQUEST";
export const SEND_TODO_SUCCESS = "SEND_TODO_SUCCESS";
export const SEND_TODO_FAIL = "SEND_TODO_FAIL";

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";

export const CHANGE_TODO_STATUS_REQUEST = "CHANGE_TODO_STATUS_REQUEST";
export const CHANGE_TODO_STATUS_SUCCESS = "CHANGE_TODO_STATUS_SUCCESS";
export const CHANGE_TODO_STATUS_FAIL = "CHANGE_TODO_STATUS_FAIL";

export const SPINNER_ON = "SPINNER_ON";
export const SPINNER_OFF = "SPINNER_OFF";
